### ISSUE TITLE
Is there any alternative for invalidateSelf(Android) in HarmonyOS?

### ISSUE THREAD

**Issue by anshulgoel72** [applibgroup/HarmonyOS-Knowledgebase#56]
### Describe the query
In my project, I want to trigger the implementation in draw() that is present in Element class. In android, we have invalidateSelf to trigger the drawToCanvas(). What is the alternative in HarmonyOS?

animator.addListener(new AnimatorListenerAdapter() {
                      @Override
                      public void onAnimationRepeat(Animator animation) {
                             shiftColor(drawable.getColorMain(), drawable.getColorSub());
                             invalidateSelf();
                      }
});

### Create the query with harmonyos tag in stackoverflow and share the link here:
https://stackoverflow.com/questions/68593351/is-there-any-alternative-for-invalidateselfandroid-in-harmonyos

### Additional information

Developer Platform: Windows  
DevEco Studio version: 2.1.0.303  
SDK API version: 5  
SDK version: 2.1.1.21  
Device: Not Required  
Device OS version: Not Required

**Comment by samuel-abhishek** [comment]
As shirley rightly suggested, there is no direct alternative for invalidateSelf() in HarmonyOS to trigger the drawToCanvas() in an Element class.

But, since most of the Element objects will ideally be embedded within a Component object, you can try to acheive this functionality by triggering the drawToCanvas() from the onDraw() function of the Component class (must be implemented with DrawTask interface or create an anonymous inner class on a component object).

Please refer the below two snippets for better understanding on how to trigger the drawToCanvas() in Element class:
```
public class CustomElement extends Element {
   CustomComponent customComponent;

   public void drawToCanvas(Canvas canvas) {
        .
        .
   }
   
   public void invalidateSelf() {
      customComponent.invalidate();
   }
}

public class CustomComponent extends Component implements Component.DrawTask {

   //initialize this in constructor of the component  
   CustomElement customElement;

   public void onDraw(Component component, Canvas canvas) {
      customElement.drawToCanvas(canvas);
   }

}
```
Another way is
```
public class CustomElement extends Element {

   public void drawToCanvas(Canvas canvas) {
        .
        .
   }
}

public class MainAbilitySlice extends AbilitySlice {

   Component mComponent;
   
   public void refreshView() {
      CustomElement customElement = new CustomElement();
      mComponent.setBackground(customElement);
      mComponent.addDrawTask(new Component.DrawTask() {
          @Override
          public void onDraw(Component component, Canvas canvas) {
              customElement.drawToCanvas(canvas);
          }
      });
      mComponent.invalidate();
   }
}
```
