### ISSUE TITLE
Can any one help me with proxy server set up in setting Dev Eco Environment?

### ISSUE THREAD

**Issue by devrishikm** [applibgroup/HarmonyOS-Knowledgebase#62]
### Describe the query
Can anyone help me with the proxy server set up in setting Dev Eco Environment?

### Create the query with harmonyos tag in stackoverflow and share the link here:
https://stackoverflow.com/questions/69065556/can-anyone-help-me-with-proxy-server-set-up-in-setting-dev-eco-environment

### Additional information

Developer Platform: MAC
DevEco Studio version: 2.1.0.501
SDK API version: 5
SDK version: 2.1.1.21
Device: Simulator
Device OS version: XYZ

**Comment by GowthamRayar** [comment]
if you are behind any **firewall/proxy-server/corporate network**, you will have to configure [proxy settings][1] in DevEco Studio. Otherwise no need to configure proxy settings. Try Accessing remote device from **Tools -> DeviceManager** or try **Gradle sync some third-party dependencies**. You should be able to do.


  [1]: https://developer.harmonyos.com/en/docs/documentation/doc-guides/environment_config-0000001052902427
